model_name: "vit_small_patch16_224"
num_classes: 200
pretrained: False       # [핵심] Scratch
image_size: 224

# Scratch 학습용 설정
batch_size: 64
epochs: 50
learning_rate: 1e-4     # AdamW 기본 LR
weight_decay: 0.05      # 강한 규제
optimizer: "adamw"
device: "cuda"