# @package _global_

model:
  name: vit_small_patch16_224
  num_classes: 200
  pretrained: false
  image_size: 224
  cfg_name: vit_small

train:
  epochs: 50
  batch_size: 64
  learning_rate: 1e-4
  weight_decay: 0.05
  optimizer: adamw
  device: cuda
  data_root: './data/CIFAR-10-C'