model_name: "resnet50"
num_classes: 10         # CIFAR10이면 10
pretrained: True        
image_size: 32

# Fine-tuning 설정 (LR을 줄임)
batch_size: 64
epochs: 20              
learning_rate: 0.01     # Scratch의 1/10 수준으로 줄여서 미세 조정
weight_decay: 5e-4
optimizer: "sgd"
momentum: 0.9
device: "cuda"