model_name: "resnet50"
num_classes: 10         # CIFAR10이면 10
pretrained: False       
image_size: 32

# Scratch 학습용 설정
batch_size: 64
epochs: 50
learning_rate: 0.1      # 큰 LR
weight_decay: 5e-4
optimizer: "sgd"
momentum: 0.9
device: "cuda"