# @package _global_

model:
  name: vit_small_patch16_224
  num_classes: 10
  pretrained: true
  image_size: 224
  cfg_name: vit_small_pretrained

train:
  epochs: 20
  batch_size: 64
  learning_rate: 1e-5
  weight_decay: 1e-4
  optimizer: adamw
  device: cuda
  data_root: './data/CIFAR-10-C'